version: "3.8"

services:
  # === MySQL Service ===
  mysql:
    image: mysql:8.0
    container_name: databse_d
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # === Next.js en Producción ===
  d_next_prod:
    container_name: d_next_prod
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  # === Next.js en Desarrollo ===
  d_next_dev:
    container_name: d_next_dev
    restart: unless-stopped
    build:
      context: .
      target: development
      args:
        - PORT=${PORT}
    ports:
      - "3001:3000" # Mapea el puerto 3000 del contenedor al 3001 del host
      - "9229:9229"
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - CHOKIDAR_INTERVAL=0.01
      - HOST=0.0.0.0
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - mysql

volumes:
  node_modules:
  mysql_data:
